GET http://localhost:8081/api/posts
Accept: application/json

###
GET http://localhost:8081/api/posts/63e950f501d1b8ba104809f7
Accept: application/json
###

POST http://localhost:8081/api/posts
Content-Type: application/json

{
  "topic": "pop5",
  "text": "post content5"
}
###

###
PUT http://localhost:8081/api/posts/63e9fe6e8056d21110793bf7
Content-Type: application/json

{
  "topic": "put52",
  "text": "post5 content2"
}
###
PUT http://localhost:8081/api/posts/63e9fe6e8056d21110793bf7
Content-Type: application/json

{
  "topic": "put57"
}

###
GET http://localhost:8081/api/posts/63e9fe6e8056d21110793bf7
Accept: application/json
###

DELETE http://localhost:8081/api/posts/63e9e9c6b39598e7d4e2ed71
Content-Type: application/json
###
GET http://localhost:8081/api/posts/63e9e9c6b39598e7d4e2ed71
Accept: application/json
###


